config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    # TOPページ
    root to: 'top#index'
    # 商品ページ
    resources :products,   only: [:show]
    # カテゴリーページ
    resources :categories, only: [:show], controller: 'taxons'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  def self.get_option_values_with_presentation(presentation)
    option_type = includes(:option_values).find_by(presentation: presentation)
    option_type&.option_values || []
  end
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  # 引数の Taxon に属し、かつ選択中の OptionValue に属する商品の数をカウント
  def num_of_products(taxon)
    product_ids_with_option_value(taxon).uniq.count
  end

  def product_ids_with_option_value(taxon)
    variants.pluck(:product_id) & taxon.self_and_descendant_products.ids
  end

  # 引数の Taxon に、選択中の OptionValue の Variant をもつ商品があるか判定
  def has_product_with?(taxon)
    num_of_products(taxon) > 0
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  def related_products(max_number)
    # 商品と同じtaxonに所属する商品リスト
    related_products = taxons.leaves.includes(:products).map(&:products).flatten.compact.uniq
    # 自分自身を除外
    related_products.delete(self)
    related_products.sample(max_number)
  end

  # 特定の OptionValue を Valiant にもつ商品を抽出
  def self.filtered_with_option_value(option_value_id)
    return all unless option_value_id
    joins(variants: :option_values).where(spree_option_values_variants: { option_value_id: option_value_id }).uniq
  end

  # 特定の OptionValue に所属する Variant をひとつ取得
  def self_or_variant_with_option_value(option_value_id = nil)
    return self unless option_value_id
    variants.joins(:option_values_variants).find_by(spree_option_values_variants: { option_value_id: option_value_id })
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  # 自身と子孫カテゴリーの商品の集合を返す
  def self_and_descendant_products
    Spree::Product.includes(:taxons).where(spree_taxons: {id: self_and_descendants})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_PRODUCT_PROPERTIES = 3
  MAX_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.includes(:properties, :variants).find(params[:id])
    @related_products = @product.related_products(MAX_RELATED_PRODUCTS)

    @color_id = params[:color]
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout "sample_layout"

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/taxons_controller.rb
class Potepan::TaxonsController < ApplicationController
  def show
    @taxon = Spree::Taxon.includes(:products).find(params[:id])
    @taxonomies = Spree::Taxonomy.all

    @type     = params[:type] == 'list' ? 'list' : 'grid'
    @color_id = params[:color]
    # TODO: 課題8で @size_id をここに追加

    @products = @taxon.self_and_descendant_products.filtered_with_option_value(@color_id)
    # TODO: 課題8で @size_id 絞り込みをここに追加

    # サイドメニューの色リスト
    @colors = Spree::OptionType.get_option_values_with_presentation('Color')
  end
end

app/controllers/potepan/top_controller.rb
class Potepan::TopController < ApplicationController
  MAX_NEW_PRODUCTS = 8

  def index
    @new_products = Spree::Product.order(available_on: :desc).limit(MAX_NEW_PRODUCTS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページタイトルを返す
  def full_title(page_title = '')
    base_title = 'BIGBAG Store'
    if page_title.empty?
      base_title
    else
      page_title + ' - ' + base_title
    end
  end

  # 文字列から属性名を取得
  def attr_name(str)
    str.downcase.gsub(' ', '-')
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  # ヴァリアントのセレクトボックス用の配列を返す
  def variants_array(product)
    # 配列先頭に、初期表示用のアイテムを挿入
    variants = [['Variants', '0']]
    # ヴァリアントごとに [名前, ID] の配列を追加
    product.variants.each do |variant|
      variants.push([variant.options_text, variant.id])
    end
    variants
  end
end

app/helpers/taxons_helper.rb
module TaxonsHelper
  # 当該カテゴリに色付きの Variant をもつ商品が存在したら、「色から探す」を表示
  def display_color_search?
    return if @colors.nil?
    @colors.map { |color| color.has_product_with?(@taxon) }.include?(true)
  end
end

app/views/layouts/head/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/main_wrapper/header/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to potepan_root_path, class: 'navbar-brand' do %>
        <%= image_tag("img/logo.png", :alt => "") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', potepan_root_path %></li>
        <li class="dropdown megaDropMenu">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</b></a>
          <ul class="dropdown-menu row">
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products Grid View</li>
                <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Products List View</li>
                <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                <li class="listHeading">Others</li>
                <li><a href="single_product.html">Single Product</a></li>
                <li><a href="cart_page.html">Cart Page</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <ul class="list-unstyled">
                <li>Checkout</li>
                <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                <li><a href="checkout_complete.html">Order Complete</a></li>
              </ul>
            </li>
            <li class="col-sm-3 col-xs-12">
              <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
          <ul class="dropdown-menu dropdown-menu-left">
            <li><a href="about_us.html">About Us</a></li>
            <li><a href="signup.html">Register</a></li>
            <li><a href="signup-login.html">Register or Login</a></li>
            <li><a href="login.html">Login</a></li>
            <li><a href="lost-password.html">Password Recovery</a></li>
            <li><a href="privacy_policy.html">Privacy Policy</a></li>
            <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
            <li><a href="404.html">404 Not Found</a></li>
            <li><a href="coming-soon.html">Coming Soon</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
            <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
            <li><a href="blog-fullwidth.html">Full Width</a></li>
            <li><a href="blog-single-fullwidth.html">Single Post</a></li>
            <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
            <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="account-dashboard.html">Dashboard</a></li>
            <li><a href="account-profile.html">Profile</a></li>
            <li><a href="account-all-orders.html">All Orders</a></li>
            <li><a href="account-single-order.html">Single Order</a></li>
            <li><a href="account-wishlist.html">Wishlist</a></li>
            <li><a href="account-address.html">Address</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(related_product.images.first.attachment.url(:product), :alt => related_product.name) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, 'Single Product') %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_root_path %>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner" id="image-carousel">
                <% @product.images.each_with_index do |image, i| %>
                  <div class="item<%= ' active' if i.zero? %>" data-thumb="<%= i %>">
                    <%# 商品画像 (非ヴァリアント) %>
                    <%= image_tag image.attachment.url(:large), id: 'variant_image_0' %>
                    <%# 商品画像 (ヴァリアント、ロード時は非表示 %>
                    <% if @product.has_variants? %>
                      <% @product.variant_images.where(position: i + 1).each do |variant_image| %>
                        <%= image_tag variant_image.attachment.url(:large), id: "variant_image_#{variant_image.viewable_id}", style: 'display: none;' %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner" id="thumbnail-carousel">
                  <% @product.images.each_with_index do |thumbnail, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%# サムネイル画像 (非ヴァリアント) %>
                      <%= image_tag thumbnail.attachment.url(:small), id: 'variant_thumb_0' %>
                      <%# サムネイル画像 (ヴァリアント、ロード時は非表示) %>
                      <% if @product.has_variants? %>
                        <% @product.variant_images.where(position: i + 1).each do |variant_thumbnail| %>
                          <%= image_tag variant_thumbnail.attachment.url(:small), id: "variant_thumb_#{variant_thumbnail.viewable_id}", style: 'display: none;' %>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">

              <li>
                <%= link_to potepan_category_path(@product.taxons.first().root.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
              <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
            </ul>
            <h2><%= @product.name %></h2>
            <h3 id="prices">
              <%# ヴァリアントを持っている場合、ロード時は商品デフォルトの価格を表示し、ヴァリアント選択時にJSで表示切り替え %>
              <% if @product.has_variants? %>
                <% product_prices = @product.prices.where(variant_id: Spree::Variant.where(product_id: @product.id).where(position: @product.prices.minimum(:position))) %>
                <span id="product_prices">
                  <%= @product.display_price %>
                </span>
                <% @product.variants.each do |variant| %>
                  <span id="variant_prices_<%= variant.id %>" style="display: none;">
                    <%= variant.display_price %>
                  </span>
                <% end %>
              <% else %>
                <%= @product.display_price %>
              <% end %>
            </h3>
            <p><%= @product.description %></p>
            <%# ヴァリアント存在時はセレクトボックスを表示 %>
            <% if @product.has_variants? %>
              <span class="quick-drop">
                <%= select_tag 'variants', options_for_select(variants_array(@product), @product.self_or_variant_with_option_value(@color_id).id), class: 'select-drop' %> 
              </span>
            <% end %>
            <span class="quick-drop resizeWidth">
              <select name="quantity" id="quantity" class="select-drop">
              <!--   <option value="0">Qty</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <% if @product.product_properties.present? %>
              <%# 表示するプロパティ数の上限を指定して切り出し %>
              <% product_properties = @product.product_properties[0, Potepan::ProductsController::MAX_PRODUCT_PROPERTIES] %>
              <div class="tabArea">
                <ul class="nav nav-tabs">
                  <%# プロパティ一覧 %>
                  <% product_properties.each_with_index do |product_property, i| %>
                    <li<% if i == 0 %> class="active"<% end %>><a data-toggle="tab" href="#<%= attr_name(product_property.property.presentation) %>"><%= product_property.property.presentation %></a></li>
                  <% end %>
                </ul>
                <div class="tab-content">
                  <%# プロパティ %>
                  <% product_properties.each_with_index do |product_property, i| %>
                    <div id="<%= attr_name(product_property.property.presentation) %>" class="tab-pane fade<% if i == 0 %> in active<% end %>">
                      <p><%= product_property.value %></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: 'related_product', collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/taxons/_grid_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.self_or_variant_with_option_value(@color_id).display_image.attachment.url, :alt => product.name) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id, color: @color_id) do %>
        <h5><%= product.name %></h5>
      <% end %>
      <h3><%= product.display_price %></h3>
    </div>
  </div>
</div>

app/views/potepan/taxons/_list_product.html.erb
<div class="col-xs-12">
  <div class="media">
    <div class="media-left">
      <%= image_tag(product.self_or_variant_with_option_value(@color_id).display_image.attachment.url, :alt => product.name) %>
      <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to product.name, potepan_product_path(product.id, color: @color_id) %></h4>
      <p><%= product.description %></p>
      <h3><%= product.display_price %></h3>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
        <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
</div>

app/views/potepan/taxons/_side_bar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% @taxonomies.each do |taxonomy| %>
            <% collapse_name = "taxonomy-#{taxonomy.id}" %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#<%= collapse_name %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
              <ul id="<%= collapse_name %>" class="collapse collapseItem">
                <% taxonomy.taxons.leaves.each do |taxon| %>
                  <li>
                    <%= link_to potepan_category_path(taxon.id, type: @type) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %> <span>(<%= taxon.products.count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default priceRange">
    <div class="panel-heading">値段から探す</div>
    <div class="panel-body clearfix">
      <div class="price-slider-inner">
        <span class="amount-wrapper">
          <input type="text" id="price-amount-1" readonly>
          <strong>-</strong>
          <input type="text" id="price-amount-2" readonly>
        </span>
        <div id="price-range"></div>
      </div>
      <input class="btn btn-default" type="submit" value="絞り込む">
      <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
    </div>
  </div>
  <%# 当該カテゴリに色付きの Variant をもつ商品が存在したら、「色から探す」を表示 %>
  <% if display_color_search? %>
    <div class="panel panel-default filterNormal">
      <div class="panel-heading">色から探す</div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @colors.each do |color| %>
            <%# 当該色の Variant をもつ商品が存在したら、色名を表示 %>
            <% if color.has_product_with?(@taxon) %>
              <li>
                <%= link_to potepan_category_path(@taxon.id, type: @type, color: color.id) do %>
                  <%= color.name %><span>(<%= color.num_of_products(@taxon) %>)</span>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <li><a href="#">S<span>(15)</span></a></li>
        <li><a href="#">M<span>(10)</span></a></li>
        <li><a href="#">L<span>(7)</span></a></li>
        <li><a href="#">XL<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/taxons/show.html.erb
<% provide(:title, @taxon.name) %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= @taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <!-- SIDE BAR -->
      <%= render 'potepan/taxons/side_bar' %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <%= button_tag class: "btn btn-default#{' active' if @type == 'grid'}", onclick: "window.location.href='#{potepan_category_path(@taxon.id, type: 'grid', color: @color_id)}'" do %>
                <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
              <% end %>
              <%= button_tag class: "btn btn-default#{' active' if @type == 'list'}", onclick: "window.location.href='#{potepan_category_path(@taxon.id, type: 'list', color: @color_id)}'" do %>
                <i class="fa fa-th" aria-hidden="true"></i><span>List</span>
              <% end %>
            </div>
          </div>
        </div>
        <% if @type == 'grid' %>
          <div class="row" id="grid-box">
            <%= render partial: 'grid_product', collection: @products, as: :product %>
          </div>
        <% end %>
        <% if @type == 'list' %>
          <div class="row productListSingle" id="list-box">
            <%= render partial: 'list_product', collection: @products, as: :product %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/potepan/top/_new_product.html.erb
<div class="slide">
  <div class="productImage">
    <%= image_tag(new_product.images.first.attachment.url(:product), :alt => new_product.name) %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption">
    <%= link_to potepan_product_path(new_product.id) do %>
      <h5><%= new_product.name %></h5>
      <h3><%= new_product.display_price %></h3>
    <% end %>
  </div>
</div>